# labeler "full" schema

# enable labeler on issues, prs, or both.
enable:
  issues: true
  prs: true
# comments object allows you to specify a different message for issues and prs

comments:
  issues: |
    Thanks for opening this issue!
    I have applied any labels matching special text in your title and description.
    Please review the labels and make any necessary changes.
  prs: |
    Thanks for the contribution!
    I have applied any labels matching special text in your title and description.
    Please review the labels and make any necessary changes.
# Labels is an object where:
# - keys are labels
# - values are objects of { include: [ pattern ], exclude: [ pattern ] }
#    - pattern must be a valid regex, and is applied globally to
#      title + description of issues and/or prs (see enabled config above)
#    - 'include' patterns will associate a label if any of these patterns match
#    - 'exclude' patterns will ignore this label if any of these patterns match
labels:
  'API Call':
    include:
      - '\blabel-api-call\b'
    exclude: []
  'bug':
    include:
      - '\blabel-bug\b'
    exclude: []
  'do not merge':
    include:
      - '\blabel-do-not-merge\b'
    exclude: []
  'doc required':
    include:
      - '\blabel-doc-required\b'
    exclude: []
  'Documentation':
    include:
      - '\blabel-documentation\b'
    exclude: []
  'enhancement':
    include:
      - '\blabel-enhancement\b'
    exclude: []
  'good first issue':
    include:
      - '\blabel-good-first-issue\b'
    exclude: []
  'HA':
    include:
      - '\blabel-ha\b'
    exclude: []
  'helm':
    include:
      - '\blabel-helm\b'
    exclude: []
  'help wanted':
    include:
      - '\blabel-help-wanted\b'
    exclude: []
  'hold':
    include:
      - '\blabel-hold\b'
    exclude: []
  'JMESPath':
    include:
      - '\blabel-jmespath\b'
    exclude: []
  'LFX':
    include:
      - '\blabel-lfx\b'
    exclude: []
  'prometheus':
    include:
      - '\blabel-prometheus\b'
    exclude: []
  'question':
    include:
      - '\blabel-question\b'
    exclude: []
  'sample policy':
    include:
      - '\blabel-sample-policy\b'
    exclude: []
  'wip':
    include:
      - '\blabel-wip\b'
    exclude: []  